name: Deploy to aaPanel VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            cd /www/wwwroot/fireguard-LBS
            
            # Izinkan Git berjalan
            git config --global --add safe.directory /www/wwwroot/fireguard-LBS
            
            # Tarik update terbaru
            git pull origin main
            
            # Install package baru & build
            npm install
            rm -rf .next/cache
            npm run build
            
            # Restart menggunakan script rahasia bawaan aaPanel agar tersinkronisasi dengan GUI
            pkill -u www -f "node server.js" || true
            sudo -u www bash /www/server/nodejs/vhost/scripts/siagabencana.sh
            
            # Install package wa-server & Restart wa-server menggunakan PM2
            cd /www/wwwroot/fireguard-LBS/wa-server
            npm install
            pm2 restart wa-server || pm2 start index.js --name "wa-server"

